services:
  - type: web
    plan: free
    name: team-name-voting
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
